name: Django Test Workflow with PostgreSQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest
    env:
      PSQL_USERNAME: german_martinez
      PSQL_PASS: SecretPassword123
      PSQL_DBNAME: german_martinezdb
      PSQL_HOST: localhost
      PSQL_PORT: 5432
    services:
      postgres:
        image: postgres:14-alpine   
        env:
          POSTGRES_USER: ${{ env.PSQL_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.PSQL_PASS }}
          POSTGRES_DB: ${{ env.PSQL_DBNAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Make Migrations
        run: |
            python manage.py makemigrations
      - name: Migrate
        run: |
            python manage.py migrate
      - name: Test
        run: |
            pytest
      - name: Run Server
        run: |
            nohup python manage.py runserver &